dist: focal
language: python
python:
  - "3.12"

services:
  - docker

branches:
  only:
    - develop
    - main
    - main-copy

env:
  global:
    - DJANGO_SETTINGS_MODULE=vocationalnyc.settings
    - PYTHONPATH=$(pwd)/VocationalNYC


before_install:
  - cd VocationalNYC
  - docker-compose -f docker-compose.ci.yml version
  - gem update --system
  - gem install bundler
  - pip install coveralls
  

install:
  - docker-compose -f docker-compose.ci.yml build

before_script:
  # Start the CI containers in detached mode
  - docker-compose -f docker-compose.ci.yml up -d
  - sleep 10
  # Run migrations and collect static files inside the app container (as root)
  - docker-compose -f docker-compose.ci.yml exec -T -u root app python manage.py makemigrations --noinput
  # - docker-compose -f docker-compose.ci.yml exec -T -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - docker-compose -f docker-compose.ci.yml exec -T -u root app python manage.py migrate --noinput
  - docker-compose -f docker-compose.ci.yml exec -T -u root app python manage.py collectstatic --noinput

script:
  - gem list logger
  # - docker-compose -f docker-compose.ci.yml exec -T -u root app python manage.py test
  - docker-compose -f docker-compose.ci.yml exec -T -u root app black --check .
  - docker-compose -f docker-compose.ci.yml exec -T -u root app flake8 .
  - docker-compose -f docker-compose.ci.yml exec -T -u root app coverage run --source=. manage.py test

after_success:  
  - docker-compose -f docker-compose.ci.yml exec -T -u root app bash -c "apt-get update && apt-get install -y git && git init && git config --global user.name 'Travis CI' && git config --global user.email 'travis@example.com' && git add . && git commit -m 'Initial commit'"
  - docker-compose -f docker-compose.ci.yml exec -T -u root app bash -c "git checkout -b $TRAVIS_BRANCH"

  # run coveralls inside the docker container
  - docker-compose -f docker-compose.ci.yml exec -T -e TRAVIS=true -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e CI=true -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -u root app pip install coveralls
  - docker-compose -f docker-compose.ci.yml exec -T -e TRAVIS=true -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e CI=true -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -u root app coveralls --verbose
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose.prod.yml build
  - docker-compose -f docker-compose.prod.yml push
  # - coveralls


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "vocationalnyc"
  env: "vocationalnyc-env"
  bucket_name: "elasticbeanstalk-us-east-1-982534395285"
  skip_cleanup: true
  on:
    branch: main
