dist: focal
language: python
python:
  - "3.12"
cache: pip

services:
  - postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=vocationalnyc.settings
    - PYTHONPATH=$PYTHONPATH:$(pwd)/VocationalNYC

install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - python manage.py test
  - black --check 
  - flake8 
  - coverage run --source=vocationalnyc manage.py test

after_success:
  - coveralls
