dist: focal
language: python
python:
  - "3.12"
cache: pip

services:
  - postgresql
  - redis-server

env:
  global:
    - DJANGO_SETTINGS_MODULE=vocationalnyc.settings
    - PYTHONPATH=$PYTHONPATH:$(pwd)/VocationalNYC

install:
  - pip install -r VocationalNYC/requirements.txt
  - pip install black flake8 coverage coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - echo "Database setting:"
  - python -c "import os; os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'VocationalNYC.vocationalnyc.settings'); import django; django.setup(); from django.conf import settings; print(settings.DATABASES)"
  - python VocationalNYC/manage.py migrate
  - python VocationalNYC/manage.py collectstatic --noinput

script:
  - cd VocationalNYC
  - python manage.py test
  - black --check .
  - flake8
  - coverage run --source=vocationalnyc manage.py test

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "djangoTutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-east-1-982534395285"
  skip_cleanup: true
  on:
    branch: main
