dist: focal
language: python
python:
  - "3.12"
cache: pip

env:
  global:
    - DJANGO_SETTINGS_MODULE=VocationalNYC.settings

install:
  - pip install -r VocationalNYC/requirements.txt
  - pip install black flake8 coverage coveralls

script:
  - python VocationalNYC/manage.py test
  - black --check VocationalNYC
  - flake8 VocationalNYC
  - coverage run --source=VocationalNYC VocationalNYC/manage.py test

after_success:
  - coveralls
