dist: focal
language: python
python:
  - "3.12"

services:
  - docker

branches:
  only:
    - develop
    - main

env:
  global:
    - DJANGO_SETTINGS_MODULE=vocationalnyc.settings
    - PYTHONPATH=$PYTHONPATH:$(pwd)/VocationalNYC

before_install:
  - cd VocationalNYC
  - docker-compose -f docker-compose.ci.yml version

install:
  - docker-compose -f docker-compose.ci.yml build

before_script:
  # Start the CI containers in detached mode
  - docker-compose -f docker-compose.ci.yml up -d
  - sleep 10
  # Run migrations and collect static files inside the app container (as root)
  - docker-compose -f docker-compose.ci.yml exec -T -u root app python manage.py makemigrations --noinput
  - docker-compose -f docker-compose.ci.yml exec -T -u root app python manage.py migrate --noinput
  - docker-compose -f docker-compose.ci.yml exec -T -u root app python manage.py collectstatic --noinput

script:
  - docker-compose -f docker-compose.ci.yml exec -T -u root app python manage.py test
  - docker-compose -f docker-compose.ci.yml exec -T -u root app black --check .
  - docker-compose -f docker-compose.ci.yml exec -T -u root app flake8 .
  - docker-compose -f docker-compose.ci.yml exec -T -u root app coverage run --source=vocationalnyc manage.py test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose.prod.yml build
  - docker-compose -f docker-compose.prod.yml push
  - coveralls


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "vocationalnyc"
  env: "vocationalnyc-env"
  bucket_name: "elasticbeanstalk-us-east-1-982534395285"
  skip_cleanup: true
  on:
    branch: main
