# Generated by Django 5.1.6 on 2025-03-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("keywords", models.CharField(blank=True, max_length=255, null=True)),
                ("course_desc", models.TextField()),
                ("cost", models.IntegerField(default=0)),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CourseDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classroom_hours", models.IntegerField()),
                ("lab_hours", models.IntegerField()),
                ("internship_hours", models.IntegerField()),
                ("practical_hours", models.IntegerField()),
            ],
        ),
    ]
