# Generated by Django 5.1.6 on 2025-03-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="provider",
            field=models.ForeignKey(
                default=999999,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.provider",
            ),
            preserve_default=False,
        ),
    ]
