# Generated by Django 5.1.6 on 2025-02-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
