# Generated by Django 5.1.6 on 2025-02-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_num', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('open_time', models.CharField(max_length=100)),
                ('provider_desc', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
