# Generated by Django 5.1.6 on 2025-03-04 19:48

import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('career_changer', 'Career Changer'), ('training_provider', 'Training Provider'), ('administrator', 'Administrator')], default='career_changer', max_length=20),
        ),
    ]
