services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kxiao02/vocationalnyc-production-app:latest
    container_name: app
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      DJANGO_ENV: production