services:
  redis:
    build:
      context: .
    image: kxiao02/vocationalnyc-production-redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: kxiao02/vocationalnyc-production-nginx:latest
    container_name: nginx
    ports:
      - "80:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    image: kxiao02/vocationalnyc-production-app:latest
    container_name: app
    depends_on:
      - redis
      - nginx
    ports:
      - "5000:5000"
    environment:
      DJANGO_ENV: production
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY