# This file is used to override the docker-compose.yml file for local development and testing purposes.
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      # - DJANGO_ENV=wobsocket_testing # Uncomment this line to test the websocket
      - DJANGO_ENV=development
    volumes:
      - .:/vocationalnyc
    ports:
      - 5000:5000
