services:
  db:
    image: postgres:13
    container_name: db
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      POSTGRES_DB: ebdb
      POSTGRES_USER: dbsuperuser
      POSTGRES_PASSWORD: RQj)!jj0AVmQRVI?FR:4.q#M_ihr
      POSTGRES_HOST: awseb-e-vtj7rkatib-stack-awsebrdsdatabase-jnh7hkwhzpgf.c8xg6uiouqs0.us-east-1.rds.amazonaws.com
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
      - redis
      - nginx
    ports:
      - 5000:5000
    environment:
      DJANGO_ENV: travis
      PYTHONPATH: /vocationalnyc
      DJANGO_SETTINGS_MODULE: vocationalnyc.settings
      SECRET_KEY: 2kr32wckkxtv&_r+p7!)o+1(jtupvk#z^uzp#y$h-=#3*7p5zr