# This file is only for development purpose
# Warning: Should not be included in the repository in production settings
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: kxiao02/vocationalnyc-production-nginx:latest
    container_name: nginx
    ports:
      - "80:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kxiao02/vocationalnyc-production-app:latest
    container_name: app
    depends_on:
      - redis
      - nginx
    ports:
      - "5000:5000"
    environment:
      DJANGO_ENV: production