# This file is used to override the docker-compose.yml file for local development and testing purposes.
services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DJANGO_ENV=test
    container_name: app
    depends_on:
      - redis
    volumes:
    - .:/vocationalnyc
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - app
      - redis
    ports:
      - "80:80"