# fly.toml app configuration file generated for vocationalnyc-wandering-silence-627 on 2025-05-04T01:38:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vocationalnyc-wandering-silence-627'
primary_region = 'ewr'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  REDIS_URL = 'redis://default:959b05d26f6649a48c830da4f6034342@fly-vocationalnyc-redis.upstash.io:6379'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
